<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var $block \Magento\Sales\Block\Order\Info */

// @codingStandardsIgnoreFile
?>
<?php $order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php echo $block->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
    <?php if (!$order->getIsVirtual()): ?>
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?php echo $block->escapeHtml(__('Shipping Address')) ?></span></strong>
            <div class="box-content">
                <address><?php /* @noEscape */ echo $block->getFormattedAddress($order->getShippingAddress()); ?></address>
            </div>
        </div>

        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?php echo $block->escapeHtml(__('Shipping Method')) ?></span>
            </strong>
            <div class="box-content">
            <?php if ($order->getShippingDescription()): ?>
                <?php echo $block->escapeHtml($order->getShippingDescription()) ?>
            <?php else: ?>
                <?php echo $block->escapeHtml(__('No shipping information available')) ?>
            <?php endif; ?>
            <?php echo $block->getChildHtml('aw_delivery_date') ?>
            </div>
        </div>
    <?php endif; ?>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?php echo $block->escapeHtml(__('Payment Method')) ?></span>
            </strong>
            <div class="box-content">
                <?php echo $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
