<?php
/*
 * @author   Zemi <cskh.zemifashion@gmail.com>
 * @copyright Copyright (c) 2021 Zemi <cskh.zemifashion@gmail.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/** @var $block \Zemi\FacebookChat\Block\Messenger */
?>
<?php if ($block->isEnabledFacebookChat()) : ?>
    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                xfbml: true,
                version: 'v6.0'
            });
        };
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = '<?= $block->getViewFileUrl("Zemi_FacebookChat::js/xfbml.customerchat");?>';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="fb-customerchat" attribution=install_email
         page_id="<?= /* @escapeNotVerified */ $block->getFacebookPageId(); ?>"
         theme_color="<?= /* @escapeNotVerified */ $block->getFacebookColor(); ?>">
    </div>
<?php endif; ?>
<script>
    require(['jquery'], function($){
        $(document).ready(function () {
            setTimeout(function () {
                $('.fb_dialog_content > iframe').css('bottom','10%')
            }, 5000);
        });
    });
</script>
