<?php
    /**
     * @var Mirasvit\CacheWarmer\Block\Adminhtml\Info\Message
     */
?>
<?php if ($message = $block->getShowMessage()): ?>
    <div class="admin__data-grid-outer-wrap">
        <div class="message-system-inner">
            <div class="message-system-short-wrapper">
                <div class="message message-warning">
                    <?= /* @escapeNotVerified */ $message ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
