<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Zemi\SalesEmail\Block\Order\Email\Items\DefaultItems */

$_item = $block->getItem();
$_order = $_item->getOrder();
$_productImage = $_item->getProductImage($_item->getSku());
?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder(); ?>
<?php $_productImage = $block->getProductImage($_item->getSku());?>
<tr>
    <td style="border: none;">
        <div class="rosa-order-item" style="width: 100%;">
            <div class="rosa-product-info-left" style="width: 34%; float: left;">
                <img src="<?= $_productImage ?>" width="90" alt="<?= $block->escapeHtml($_item->getName()) ?>">
            </div>
            <div class="rosa-product-info-right" style="width: 64%; float: right">
                <p class="rosa-item-name"><?= /* @noEscape */ __("Sản phẩm : ")?><a href="<?= $productUrl ?>"><?= $block->escapeHtml($_item->getName()) ?></a></p>
                <p class="rosa-item-qty"><?= /* @noEscape */ __("Số lượng : ") ?><?= (float) $_item->getQty() ?></p>
                <p class="rosa-item-price"><?= /* @noEscape */ __("Giá : ")?><?= /* @noEscape */ $block->getItemPrice($_item->getOrderItem()) ?></p>
                <p class="rosa-item-sku"><?= /* @noEscape */ __("Mã sản phẩm : ")?><?= $block->escapeHtml($block->getSku($_item)) ?></p>
                <?php if ($block->getItemOptions()) : ?>
                    <?php foreach ($block->getItemOptions() as $key => $option) : ?>
                        <p class="rosa-item-<?= $key ?>"><?= $block->escapeHtml($option['label']) . ": "?><?= $block->escapeHtml($option['value']) ?></p>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
                <?php endif; ?>
                <?= $block->escapeHtml($_item->getDescription()) ?>
            </div>
        </div>
    </td>
</tr>
