<?php
use Magento\Framework\App\Action\Action;
$i = 0;
?>
<?php foreach ($collection as $_product): ?>
    <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
        <div class="owl-carousel owl-theme">
    <?php endif ?>
    <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        <div class="category-products">
        <ol class="product-items <?= $type; ?> <?= $carousel && $row == 1 ? ' owl-carousel owl-theme' : '' ?> <?= !$carousel ? ' row': '' ?>">
    <?php endif ?>

    <?php $i++ ?>
    <li class="product-item<?= !$carousel ? ' col-6 col-sm-4 col-md-3' : '' ?>">
        <div class="product-item-info">
            <div class="product-show">
                <a href="<?= $block->getProductUrl($_product) ?>" class="product-item-photo">
                    <?= $block->getImage($_product, $image)->toHtml(); ?>
                    <?php if ($labelHelper->getDiscountPercent($_product)) : ?>
                        <span class="discount-percent"><?= $labelHelper->getDiscountPercent($_product); ?></span>
                    <?php endif;?>
                </a>
                <?php if ($block->getData('product_style') != 4) : ?>
                    <div class="product-btn">
                        <div class="row no-gutters text-center">
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                <div class="col btn-wishlist">
                                    <button type="button"
                                       data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_product); ?>'
                                       class="action towishlist mb-tooltip" data-action="add-to-wishlist"
                                       title="<?= /* @escapeNotVerified */ __('Add to Wishlist') ?>"><i class="mbi mbi-heart"></i></button>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="product details product-item-details">
                <h3 class="product-item-name">
                    <a title="<?= $block->escapeHtml($_product->getName()) ?>"
                       href="<?= /* @escapeNotVerified */ $block->getProductUrl($_product) ?>"
                       class="product-item-link">
                        <?= $block->escapeHtml($_product->getName()) ?>
                    </a>
                </h3>
                <?php if ($showRating) : ?>
                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                <?php endif; ?>
                <div class="price-wrap">
                    <?= /* @escapeNotVerified */ $block->getProductPriceHtml(
                        $_product,
                        \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                        \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                        [
                            'price_id_suffix' => '-' . $pricePrefixId
                        ]
                    ) ?>
                </div>
            </div>
        </div>
    </li>
    <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ol>
        </div>
    <?php endif ?>
    <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
        </div>
    <?php endif ?>
<?php endforeach ?>
