<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>
<div class="container">
    <div class="row no-gutters zemi-intro-block">
        <div class="col-lg-12 col-img">
            <div class="img wow fadeIn animated">
                <div class="section eshop-intro-section" id="about">
                    <div class="container">
                        <div class="zemi-title-text-center wow fadeInUpSmall animated">
                            <h3><?= __('TRẢI NGHIỆM PHONG CÁCH MUA SẮM TRỰC TUYẾN AN TOÀN CHẤT LƯỢNG TỪ ZEMI') ?></h3>
                            <p><?= __('Chính thức thành lập vào ngày 01/01/2021, trang mua sắm thời trang trực tuyến chính thức
                                và duy nhất của ZEMI:') ?><span>&nbsp;</span>
                                <a href="https://zemi.vn/" target="_blank" rel="noopener"><?= __('www.Zemi.vn') ?></a>
                                <?= __(' hứa hẹn giải quyết bài toán mua sắm trực tuyến an toàn, sản phẩm chất lượng và dịch vụ chu
                                đáo cho khách hàng') ?></p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-img">
                            <div class="img wow fadeIn animated">
                                <img class="img-gioi-thieu"
                                     src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-gioi-thieu.jpg')?>"
                                     alt="">
                            </div>
                        </div>
                        <div class="col-lg-6 col-text">
                            <div class="text">
                                <div class="zemi-title__sm wow fadeInUpSmall animated">
                                    <h5><?= __('Đáp ứng được nhu cầu mua sắm của những "tín đồ" thời trang, thỏa mãn nhu cầu mua sắm') ?></h5>
                                </div>
                                <div class="wow fadeInUpSmall animated" data-wow-delay="0.2s">
                                    <p><?= __('ZEMI sẽ mang lại cho khách hàng những trải nghiệm mua sắm thời trang hàng hiệu
                                        trực tuyến thú vị từ các thương hiệu thời trang quốc tế và trong nước, cam kết
                                        chất lượng phục vụ hàng đầu cùng với những bộ sưu tập quần áo nam nữ khổng lồ từ
                                        trang phục, phụ kiện cho phụ nữ với những xu hướng thời trang mới nhất. Bạn có
                                        thể tìm thấy những bộ trang phục mình muốn từ những bộ đồ ở nhà thật thoải mái
                                        hay tự tin trong những bộ trang phục công sở phù hợp. Những trải nghiệm mới chỉ
                                        có ở trang mua sắm hàng hiệu trực tuyến ZEMI.') ?></p>
                                    <p><?= __('ZEMI sẽ gợi ý cho bạn những món quà thật ý nghĩa để tặng người thân, bạn bè.
                                        Chúng tôi sẽ làm bạn hài lòng với sự lựa chọn của mình bằng giá tốt nhất và chất
                                        lượng dịch vụ hoàn hảo của ZEMI.') ?></p>
                                    <p><?= __('ZEMI luôn cập nhật những xu hướng thời trang phong cách nhất đều có ở ZEMI.') ?></p>
                                    <p><?= __('Đặc biệt, ZEMI còn có nhiều đợt khuyến mãi, giảm giá đặc biệt với giá tốt nhất. Thời trang hàng hiệu chất lượng cao, phù hợp túi tiền - chỉ có ở ZEMI!.') ?></p>
                                    <p><?= __('Bạn có thể mua sắm thoải mái trên ZAREEN mà không có bất kỳ lo lắng nào: ')?>
                                        <a href="chinh-sach-doi-tra.html"><?= __('trả hàng trong vòng 3 ngày ')?></a>
                                     <?= __('kể từ ngày nhận hàng. Nếu bạn có bất kì câu hỏi nào về các sản phẩm của chúng tôi từ trang phục nữ hãy liên hệ ngay tới bộ phận chăm sóc khách hàng.') ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row no-gutters zemi-intro-block">
                        <div class="col-lg-6 col-text">
                            <div class="text">
                                <div class="zemi-title__sm wow-fadeInUpSmall-animated">
                                    <h5><?= __('Mua sắm thả ga tại Zemi chỉ với 1 click chuột')?></h5>
                                </div>
                                <div class="wow fadeInUpSmall animated" data-wow-delay="0.2s">
                                    <p><?= __('Chỉ với một thao tác “Chọn mua” đơn giản, bạn đã có thể thoả sức mua sắm những
                                        món đồ chất lượng, làm mới phong cách thời trang của bạn, đồng
                                        thời trải nghiệm dịch vụ đổi trả hàng trong vòng 3 ngày sau khi mua. Tại
                                        Zemi.Vn, bạn sẽ cảm giác như đang đi shopping Zemi tại nhà, với đa dạng sản
                                        phẩm thuộc các mặt hàng như:')?></p>
                                    <ul class="row" style="list-style-type: none;">
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-icon-qua-nao-nam.jpg')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Thời trang Nam')?></span>
                                        </li>
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-thoi-trang-nu.png')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Thời trang Nữ')?></span>
                                        </li>
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-trang-phuc-dong.png')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Trang phục đông')?></span>
                                        </li>
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-mebe-dochoi.png')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Mẹ & bé, đồ chơi')?></span>
                                        </li>
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-icon-giay-boot.png')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Giày dép & Boot')?></span>
                                        </li>
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-balo.png')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Balo & Túi xách')?></span>
                                        </li>
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-phukien-lamdep.png')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Phụ kiện & Làm đẹp')?></span>
                                        </li>
                                        <li class="col-lg-4 col-md-4 col-sm-6 col-6">
                                            <img src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-do-dung-ca-nhan.png')?>" style="max-width: 20px" alt="">
                                            <span><?= __('Đồ chơi & Giải trí')?></span>
                                        </li>
                                    </ul>
                                    <p><?= __('Ngoài ra, Zemi có rất nhiều chương trình ưu đãi hấp dẫn hàng tháng, cho gia đình bạn nhiều cơ hội mua sắm tiết kiệm và tiện lợi.')?></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-img">
                            <div class="img-wow-fadeIn-animated">
                                <img class="img-gioi-thieu" src="<?= $block->getViewFileUrl('Zemi_CmsTemplate::images/zemi-shopping.jpg')?>" alt="">
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="hr-end-section">
                <div class="section zemi-why-section" id="adva">
                    <div class="container">
                        <div class="zemi-title__text-center">
                            <h3><?= __('4 LÝ DO ĐỂ MUA SẮM TRỰC TUYẾN TẠI ZEMI SHOP')?></h3>
                        </div>
                        <div class="row zemi-why-row">
                            <div class="col-12 col-lg-3 col-sm-6 zemi-fadeInUpSmall-animated">
                                <div class="zemi-why-box">
                                    <div class="img">
                                        <img src="https://www.aeon.com.vn/wp-content/themes/aeon/assets/images/aeon-eshop/why-1.png" alt="">
                                    </div>
                                    <div class="text">
                                        <h4><?= __('ĐA DẠNG HÀNG HOÁ')?></h4>
                                        <p><?= __('AeonEshop như Siêu thị AEON thu nhỏ, cung cấp đa dạng chủng loại sản phẩm, từ
                                            thực phẩm hàng ngày, thời trang, đến điện máy, gia dụng, dụng cụ thể thao –
                                            dã ngoại,.. Phục vụ đầy đủ cho nhu cầu mua sắm của người Việt.')?></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-3 col-sm-6 zemi-fadeInUpSmall-animated">
                                <div class="zemi-why-box">
                                    <div class="img">
                                        <img src="https://www.aeon.com.vn/wp-content/themes/aeon/assets/images/aeon-eshop/why-2.png" alt=""></div>
                                    <div class="text">
                                        <h4>MIỄN PHÍ VẬN CHUYỂN</h4>
                                        <p>AeonEshop giao hàng miễn phí toàn quốc với đơn hàng từ 300.000 đồng.<br>Thời
                                            gian AeonEshop giao hàng từ thứ 2 đến thứ 7 hàng tuần, từ 8:00 đến 22:00.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-3 col-sm-6 zemi-fadeInUpSmall-animated">
                                <div class="zemi-why-box">
                                    <div class="img"><img
                                                src="https://www.aeon.com.vn/wp-content/themes/aeon/assets/images/aeon-eshop/why-4.png"
                                                alt=""></div>
                                    <div class="text">
                                        <h4>ĐỔI TRẢ DỄ DÀNG</h4>
                                        <p>AeonEshop nhận đổi trả trong vòng 10 ngày đối với sản phẩm điện máy và 14
                                            ngày cho các sản phẩm còn lại (ngoại trừ đồ tươi sống, đồ lót, mỹ phẩm, các
                                            sản phẩm thanh lý, hàng điện máy đã kích hoạt bảo hành).</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-3 col-sm-6 zemi-fadeInUpSmall-animated">
                                <div class="zemi-why-box">
                                    <div class="img"><img
                                                src="https://www.aeon.com.vn/wp-content/themes/aeon/assets/images/aeon-eshop/why-5.png"
                                                alt=""></div>
                                    <div class="text">
                                        <h4>ƯU ĐÃI HẤP DẪN</h4>
                                        <p>Mỗi ngày, AeonEshop đều mang đến nhiều ưu đãi hấp dẫn dành cho nhiều mặt hàng
                                            khác nhau. Ngoài ra, AeonEshop còn hợp tác với nhiều thương hiệu để dành
                                            riêng cho khách hàng nhiều lợi ích khi mua sắm.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
