{{widget type="Zemi\Productslider\Block\Widget\Product" category_ids="4,29"}} <!-- End BLock top --> <!-- Start Block Deal of the day -->
<div class="deal-block-top-wrap">{{widget type="MageBig\WidgetPlus\Block\StaticPlus" block_id="deal-block-top-v05" countdown="1" slider="0" background_type="0" template="widget/static_block.phtml"}}</div>
<!-- End Block Deal of the day --> <!-- Start Block banner middle -->
<div class="block-banner block-banner-05">
    <div class="row">
        <div class="col-12"><a class="banner hover-effect01" href="#"><img class="img-fluid" src="{{media url=&quot;wysiwyg/magebig/layout05/promo01.jpg&quot;}}" alt=""></a></div>
    </div>
</div>
<!-- End Block banner middle --> <!-- Start Block Consumer Electronic -->
<div class="block-product-layout-wrap block-main-product">
    <div class="top-title">
        <h2 class="title"><a href="{{store url='thoi-trang-nu.html'}}"><i class="mbi mbi-shirt"></i> <span>Thời trang nữ</span></a></h2>
        <ul class="list-category">
            <li><a class="extra-link" href="{{store url='thoi-trang-nu/dam-vay.html'}}">Đầm váy &nbsp;</a></li>
            <li><a class="extra-link" href="{{store url='thoi-trang-nu/ao-so-mi.html'}}">Sơ mi &nbsp;</a></li>
            <li><a class="extra-link" href="{{store url='thoi-trang-nu/vay-ngan-chan-vay.html'}}">Váy, chân váy</a></li>
        </ul>
    </div>
    <div class="block-product-inner">
        <div class="row no-gutters">
            <div class="col-12 col-md-7 col-lg-8 col-xl-9 block-product-col-left">
                <div class="block-product-layout-inner">
                    <div class="block-product-bn block-product-bn-01">
                        <div class="owl-carousel owl-theme">
                            <div class="item-slider"><a href="#"><img class="lazyOwl" src="{{media url='wysiwyg/magebig/layout05/b1.png'}}" alt=""></a></div>
                            <div class="item-slider"><a href="#"><img class="lazyOwl" src="{{media url='wysiwyg/magebig/layout05/b2.jpg'}}" alt=""></a></div>
                        </div>
                    </div>
                    <script type="text/javascript" xml="space">
                        // <![CDATA[
                        require(['jquery', 'owlWidget'], function ($) {
                            $(function() {
                                $('.block-product-bn-01').owlWidget({
                                    items: 1,
                                    dots: false,
                                    nav: false,
                                    loop: true,
                                    margin: 0
                                });
                            });
                        });
                        // ]]>
                    </script>
                    <div class="block-product-tab-cat">{{widget type="MageBig\WidgetPlus\Block\ProductTab" widget_tab="collections" collections="newcreated,bestseller,discount" category_ids="3,4,5,6,7,8,9" labels="Sản phẩm mới // Bán chạy // Yêu thích" period="current_year" product_style="1" cache_lifetime="86400" limit="8" slider="1" row="1" margin="30" navigation="1" paging="0" column="4" x1600="items:6" x1200="items:4" x992="items:3" x768="items:3" x576="items:2" x0="items:2" template="widget/product_tab01.phtml"}}</div>
                </div>
            </div>
            <div class="col-12 col-md-5 col-lg-4 col-xl-3">
                <div class="block-product-sidebar">{{widget type="MageBig\WidgetPlus\Block\Product" widget_title="Đề xuất cho bạn" product_type="newupdated" category_ids="4,5,6,7,9,8" product_style="5" cache_lifetime="86400" limit="6" countdown="0" slider="1" row="6" margin="30" navigation="0" paging="0" column="1" template="widget/product01.phtml"}}</div>
            </div>
        </div>
    </div>
</div>
<!-- End Block Consumer Electronic --><!-- Clothing & Appreal -->
<div class="block-product-layout-wrap block-main-product">
    <div class="top-title">
        <h2 class="title"><a href="{{store url='thoi-trang-cap-doi.html'}}"><i class="mbi mbi-shirt"></i> <span>Thời trang cặp đôi</span></a></h2>
        <ul class="list-category">
            <li><a class="extra-link" href="{{store url='thoi-trang-cap-doi/ao-phong.html'}}">Sơ mi đôi &nbsp;</a></li>
            <li><a class="extra-link" href="{{store url='thoi-trang-cap-doi/ao-so-mi.html'}}">Áo phông đôi &nbsp;</a></li>
            <li><a class="extra-link" href="{{store url='thoi-trang-cap-doi/set-do-doi.html'}}">Set đồ đôi</a></li>
        </ul>
    </div>
    <div class="block-product-inner">
        <div class="row no-gutters">
            <div class="col-12 col-md-7 col-lg-8 col-xl-9 block-product-col-left">
                <div class="block-product-layout-inner">
                    <div class="block-product-bn block-product-bn-02">
                        <div class="owl-carousel owl-theme">
                            <div class="item-slider"><a href="#"><img class="lazyOwl" src="{{media url='wysiwyg/magebig/layout05/b3.jpg'}}" alt=""></a></div>
                            <div class="item-slider"><a href="#"><img class="lazyOwl" src="{{media url='wysiwyg/magebig/layout05/b4.jpg'}}" alt=""></a></div>
                        </div>
                    </div>
                    <script type="text/javascript" xml="space">// <![CDATA[
                        require(['jquery', 'owlWidget'], function ($) {
                            $(function() {
                                $('.block-product-bn-02').owlWidget({
                                    items: 1,
                                    dots: false,
                                    nav: true,
                                    loop: true,
                                    margin: 0
                                });
                            });
                        });
                        // ]]></script>
                    <div class="block-product-tab-cat">{{widget type="MageBig\WidgetPlus\Block\ProductTab" widget_tab="collections" collections="newcreated,bestseller,discount" category_ids="10,17,18" labels="Sản phẩm mới // Bán chạy // Yêu thích" period="all_time" product_style="1" cache_lifetime="86400" limit="8" slider="1" row="1" margin="30" navigation="1" paging="0" column="4" x1600="items:6" x1200="items:4" x992="items:3" x768="items:3" x576="items:2" x0="items:2" template="widget/product_tab01.phtml"}}</div>
                </div>
            </div>
            <div class="col-12 col-md-5 col-lg-4 col-xl-3">
                <div class="block-product-sidebar">{{widget type="MageBig\WidgetPlus\Block\Product" widget_title="Đề xuất cho bạn" product_type="newcreated" category_ids="10,17,18" product_style="5" cache_lifetime="86400" limit="6" countdown="0" slider="1" row="6" margin="30" navigation="0" paging="0" column="1" template="widget/product01.phtml"}}</div>
            </div>
        </div>
    </div>
</div>
<!-- End Block Clothing & Appreal --><!-- Home, Garden & Kitchen -->
<div class="block-product-layout-wrap block-main-product">
    <div class="top-title">
        <h2 class="title"><a href="{{store url='trends.html'}}"><i class="mbi mbi-lampshade"></i> <span>Trends, sành điệu</span></a></h2>
        <ul class="list-category">
            <li><a class="extra-link" href="{{store url='trends/xu-huong.html'}}">Xu hướng &nbsp;</a></li>
            <li><a class="extra-link" href="{{store url='trends/hot.html'}}">HOT NHẤT TUẦN &nbsp;</a></li>
            <li><a class="extra-link" href="{{store url='trends/yeu-thich.html'}}">Được yêu thích</a></li>
        </ul>
    </div>
    <div class="block-product-inner">
        <div class="row no-gutters">
            <div class="col-12 col-md-7 col-lg-8 col-xl-9 block-product-col-left">
                <div class="block-product-layout-inner">
                    <div class="block-product-bn block-product-bn-02">
                        <div class="owl-carousel owl-theme">
                            <div class="item-slider"><a href="#"><img class="lazyOwl" src="{{media url='wysiwyg/magebig/layout05/b5.jpg'}}" alt=""></a></div>
                            <div class="item-slider"><a href="#"><img class="lazyOwl" src="{{media url='wysiwyg/magebig/layout05/b6.jpg'}}" alt=""></a></div>
                        </div>
                    </div>
                    <script type="text/javascript" xml="space">// <![CDATA[
                        require(['jquery', 'owlWidget'], function ($) {
                            $(function() {
                                $('.block-product-bn-02').owlWidget({
                                    items: 1,
                                    dots: false,
                                    nav: true,
                                    loop: true,
                                    margin: 0
                                });
                            });
                        });
                        // ]]></script>
                    <div class="block-product-tab-cat">{{widget type="MageBig\WidgetPlus\Block\ProductTab" widget_tab="collections" collections="newcreated,bestseller,discount" category_ids="12,13,14,15" labels="Sản phẩm mới // Bán chạy // Yêu thích" period="current_year" product_style="1" cache_lifetime="86400" limit="8" slider="1" row="1" margin="30" navigation="1" paging="0" column="4" x1600="items:6" x1200="items:4" x992="items:3" x768="items:3" x576="items:2" x0="items:2" template="widget/product_tab01.phtml"}}</div>
                </div>
            </div>
            <div class="col-12 col-md-5 col-lg-4 col-xl-3">
                <div class="block-product-sidebar">{{widget type="MageBig\WidgetPlus\Block\Product" widget_title="Đề xuất cho bạn" product_type="newupdated" category_ids="5,12,13,14,15" product_style="5" cache_lifetime="86400" limit="6" countdown="0" slider="1" row="6" margin="30" navigation="0" paging="0" column="1" template="widget/product01.phtml"}}</div>
            </div>
        </div>
    </div>
</div>
<!-- End Block Home, Garden & Kitchen --> <!-- Start Block Features -->
<div class="selling-feature-wrap">
    <div class="selling-feature">
        <div class="row align-items-center">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                <div class="media list-features">
                    <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-rocket"></i></div>
                    <div class="media-body">
                        <div class="media-heading h4">&nbsp;Giao hàng miễn phí</div>
                        <div class="text desc std">&nbsp;Cho đơn hàng 300k trở lên</div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                <div class="media list-features">
                    <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-sync2"></i></div>
                    <div class="media-body">
                        <div class="media-heading h4">&nbsp;Đổi trả trong 3 ngày</div>
                        <div class="text desc std">&nbsp;Nếu sản phẩm có vấn đề</div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                <div class="media list-features">
                    <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-credit-card2"></i></div>
                    <div class="media-body">
                        <div class="media-heading h4">&nbsp;An toàn thanh toán</div>
                        <div class="text desc std">&nbsp;Thông tin khách hàng được bảo mật</div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
                <div class="media list-features">
                    <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-bubbles"></i></div>
                    <div class="media-body">
                        <div class="media-heading h4">&nbsp;Hỗ trợ 24/7</div>
                        <div class="text desc std">&nbsp;Tất cả các ngày trong tuần</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
