<?php
/** @var $block \RosalynShop\Productslider\Block\Widget\Product */
$products = $block->getProductCollecttion();
$mediaUrl = $block->getMediaUrl();
$bannerSlider = $block->getBannerSlider();
?>
<div class="banner-slider-top">
    <div class="row">
        <div class="d-none d-md-block col-md-3"></div>
        <div class="col-12 col-xl-9">
            <div class="row no-gutters home-slider">
                <div class="col-12 col-sm-12 col-md-9">
                    <div class="item-bn-slider-05 slider-2">
                        <div class="owl-carousel owl-theme">
                            <?php foreach ($bannerSlider as $item) : ?>
                                <div class="item-slider">
                                    <a href="<?= $item['link'] ?>" alt="<?= $item['alt_text']?>">
                                        <img class="item" alt="<?= $item['alt_text']?>" src="<?= $mediaUrl .$item['resource_path'] ?>">
                                    </a>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div class="product-slider">
                        <?php
                        if ($products->count()) { ?>
                            <ol class="product-items owl-carousel">
                                <?php foreach ($products as $_product): ?>
                                    <li class="product-item">
                                        <div class="product-item-inner">
                                            <div class="product-image">
                                                <a href="<?= $_product->getProductUrl() ?>">
                                                    <img src="<?= $block->getProductImage($_product, 'product_page_image_small')?>">
                                                </a>
                                            </div>
                                            <div class="product-price"><span><?= $block->getProductPrice($_product) ?></span></div>
                                            <div class="product-title"><span><a href="<?= $_product->getProductUrl() ?>"><?= $_product->getName(); ?></a></span></div>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                            </ol>
                        <?php } ?>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-3">
                    <div class="row no-gutters rosa-no-gutters">
                        <div class="col-12 col-sm-12">
                            <div class="item-bn-inner">
                                <a href="#">
                                    <span class="item-bn hover-effect01" style="background-image: url(<?= $mediaUrl.'wysiwyg/magebig/layout05/Thi_t_k_kh_ng_t_n.png' ?>)"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(
        ['jquery', 'owlWidget'], function ($) {
            $(function() {
                $('.item-bn-slider-05').owlWidget({
                    autoplay: true,
                    items: 1,
                    dots: true,
                    nav: true,
                    loop: true,
                    margin: 0
                });

                /** Product Slider */
                $('.product-items').owlWidget({
                    loop: true,
                    responsiveClass: true,
                    pagination: false,
                    dots: false,
                    nav: true,
                    autoplay: true,
                    autoplayHoverPause: true,
                    responsive: {
                        0: {
                            items: 2
                        },
                        600: {
                            items: 3
                        },
                        1000: {
                            items: 5
                        }
                    }
                });
            });
        })
</script>