<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */ ?>
<?php $_product = $block->getProduct() ?>
<?php
/* @var $helper \Zemi\Notification\Helper\Data */
$helper = $this->helper(Zemi\Notification\Helper\Data::class);
?>
<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>
        <div class="stock available khuyen-mai" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span class="title-khuyen-mai"><?= $block->escapeHtml(__('In stock')) ?></span>
            <div class="km-content">
                <p>1. Mã: <strong class="magiamgia"><?= __($helper->voucherShop()."&nbsp;") ?></strong><?= __($helper->voucherDescribe()) ?></p>
                <p>2. FreeShip: đơn hàng từ 300K</p>
                <p>3. Đơn hàng được <a href="phuong-thuc-van-chuyen.html">vận chuyển</a> qua
                    <a href="https://jtexpress.vn/" target="_blank"> J&amp;T Express </a> hoặc
                    <a href="https://viettelpost.com.vn/" target="_blank"> Viettel Post </a></p>
                <p>4. <a href="chinh-sach-doi-tra.html">Đổi trả trong 3 ngày</a> nếu có vấn đề về sản phẩm</p>
                <p>5. Zemi cam kết chất lượng, giá cả cạnh tranh</p></div>
        </div>
    <?php else : ?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
