<?php
/*
 * @author   Zemi <cskh.zemifashion@gmail.com>
 * @copyright Copyright (c) 2021 Zemi <cskh.zemifashion@gmail.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/** @var $block \Zemi\RegionManager\Block\Adminhtml\Wards\WardsJs */
?>

<script type="text/x-magento-init">
{
    "*": {
        "Zemi_RegionManager/js/wards_js" : <?= /* @escapeNotVerified */ $block->getWardsAjaxUrl() ?>
    }
}
</script>

