<?php
/**
 *  @author   Rosalynshop <info@rosalynshop.com>
 *  @copyright Copyright (c) 2019 Rosalynshop <https://rosalynshop.com>. All rights reserved.
 *  @license   Open Software License ("OSL") v. 3.0
 */

/** @var $block \RosalynShop\RegionManager\Block\Adminhtml\Wards\WardsJs */
?>

<script type="text/x-magento-init">
{
    "*": {
        "RosalynShop_RegionManager/js/wards_js" : <?= /* @escapeNotVerified */ $block->getWardsAjaxUrl() ?>
    }
}
</script>

