<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct();
 $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<div class="social-share">
    <ul class="social-listing">
        <li class="facebook">
            <a class="trasition-all" title="<?= __('Share on Facebook') ?>" href="#" target="_blank" rel="nofollow" onclick="window.open('//www.facebook.com/sharer/sharer.php?u='+'<?= $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>');return false;"><span class="mbi mbi-facebook"></span></a>
        </li>
        <li class="twitter">
            <a class="trasition-all" href="#" title="<?= __('Share on Twitter') ?>" rel="nofollow" target="_blank" onclick="window.open('//twitter.com/share?text=<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>&amp;url=<?= $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>');return false;"><span class="mbi mbi-twitter"></span></a>
        </li>
        <li class="google-plus">
            <a class="trasition-all" href="#" title="<?= __('Share on Google Plus') ?>" rel="nofollow" target="_blank" onclick="window.open('//plus.google.com/share?url=<?= $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>');return false;"><span class="mbi mbi-google-plus"></span></a>
        </li>
        <li class="rss">
            <a href="<?= $block->getBaseUrl() ?>rss" rel="nofollow" target="_blank"><span class="mbi mbi-social-rss"></span></a>
        </li>
    </ul>
</div>
