<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
<?php if ($_shipment && $_order && $trackCollection): ?>
    <br />
    <table class="shipment-track">
        <thead>
        <tr>
            <th><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($trackCollection as $_item): ?>
            <tr>
                <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                <td>
                <?php $trackingInfo = $block->getTrackingInfoByTrackId($_item->getEntityId()); ?>
                <?php if ($trackingInfo->getUrl()): ?>
                    <a href="<?= $block->escapeHtml($trackingInfo->getUrl()) ?>" onclick="this.target='_blank'"><?= $block->escapeHtml($_item->getNumber()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($_item->getNumber()) ?>
                <?php endif; ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
