<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block \Magento\Sales\Block\Adminhtml\Order\Invoice\View\Form */

// @codingStandardsIgnoreFile
?>
<?php $invoice = $block->getInvoice() ?>
<?php $order = $invoice->getOrder() ?>
<?php echo $block->getChildHtml('order_info') ?>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Payment &amp; Shipping Method')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?> admin__fieldset-wrapper">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Payment Information')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?php echo $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency">
                    <?php echo $block->escapeHtml(__('The order was placed using %1.', $order->getOrderCurrencyCode())) ?>
                </div>
                <div class="order-payment-additional"><?php echo $block->getChildHtml('order_payment_additional'); ?></div>
            </div>
        </div>

        <?php if (!$order->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo $block->escapeHtml(__('Shipping Information')) ?></span>
                </div>
                <div class="admin__page-section-item-content shipping-description-wrapper">
                    <div class="shipping-description-title">
                        <?php echo $block->escapeHtml($order->getShippingDescription()) ?>
                    </div>
                    <div class="shipping-description-content">
                        <?php echo $block->escapeHtml(__('Total Shipping Charges')) ?>:

                        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                            <?php $excl = $block->displayShippingPriceInclTax($order); ?>
                        <?php else: ?>
                            <?php $excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                        <?php endif; ?>
                        <?php $incl = $block->displayShippingPriceInclTax($order); ?>

                        <?php /* @noEscape */ echo $excl; ?>
                        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $incl != $excl): ?>
                            (<?php echo $block->escapeHtml(__('Incl. Tax')) ?> <?php /* @noEscape */ echo $incl; ?>)
                        <?php endif; ?>
                        <div><?php echo $block->getChildHtml('shipment_tracking') ?></div>
                        <div><?php echo $block->getChildHtml('aw_delivery_date') ?></div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Items Invoiced')) ?></span>
    </div>

    <div id="invoice_item_container" class="admin__page-section-content">
        <?php echo $block->getChildHtml('invoice_items') ?>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Order Total')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Invoice History')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <?php echo $block->getChildHtml('order_comments') ?>
            </div>
        </div>

        <div id="history_form" class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Invoice Totals')) ?></span>
            </div>
            <?php echo $block->getChildHtml('invoice_totals') ?>
        </div>
    </div>
</section>
